name: time_formatter
description: Format UNIX timestamps into human-readable strings in Dart; inspired by YouTube's time formatting habits.
version: 1.0.0+4
author: Jeremi Gendron <gendronjeremi@gmail.com>
homepage: https://github.com/jeremigendron
repository: https://github.com/jeremigendron/time_formatter
issue_tracker: https://github.com/jeremigendron/time_formatter/issues
documentation: https://github.com/jeremigendron/time_formatter/tree/master/README.md

environment:
  sdk: ">=2.0.0 <3.0.0"

dev_dependencies:
  test: ^1.5.3
